services:
  - type: web
    plan: free
    name: highlightGenerator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn highlightGenerator.asgi:application -k uvicorn.workers.UvicornWorker"